#!/usr/bin/env bash
export FORCE_COLOR=1
export ELECTRON_RUN_AS_NODE=1
export AUTOFLOW_PACKAGED=true
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
if [ -f "$DIR/autoflow-vnext" ]; then
  exec "$DIR/autoflow-vnext" "$DIR/resources/app.asar/dist/cli.js" "$@"
elif [ -f "$DIR/Autoflow-vNext" ]; then
  exec "$DIR/Autoflow-vNext" "$DIR/resources/app.asar/dist/cli.js" "$@"
else
  exec "$DIR/autoflow" "$DIR/resources/app.asar/dist/cli.js" "$@"
fi
