const log = require('../utils/logger');
const inquirer = require('inquirer');
const fs = require('fs');
const path = require('path');

async function init(cmdObj) {
    log.header('AUTOFLOW INITIALIZATION');
    log.info('Refer to your server provider for IP and SSH details.\n');

    const questions = [
        {
            type: 'input',
            name: 'projectName',
            message: 'Project Name (for Docker container):',
            default: path.basename(process.cwd()).toLowerCase().replace(/[^a-z0-9-_]/g, '-'),
            validate: input => input ? true : 'Project name is required'
        },
        {
            type: 'input',
            name: 'gitRepo',
            message: 'Git Repository URL (HTTPS recommended):',
            validate: input => input ? true : 'Git URL is required'
        },
        {
            type: 'input',
            name: 'serverIp',
            message: 'Remote Server IP Address:',
            validate: input => /^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$/.test(input) ? true : 'Invalid IP format'
        },
        {
            type: 'input',
            name: 'sshUser',
            message: 'SSH Username:',
            default: 'root'
        },
        {
            type: 'input',
            name: 'sshPort',
            message: 'SSH Port:',
            default: '22'
        },
        {
            type: 'input',
            name: 'sshKeyPath',
            message: 'Path to SSH Private Key (Absolute Path):',
            default: `${process.env.USERPROFILE || process.env.HOME}/.ssh/id_rsa`.replace(/\\/g, '/')
        },
        {
            type: 'input',
            name: 'appPort',
            message: 'Application Port (Container -> Host):',
            default: '3000'
        }
    ];

    try {
        const answers = await inquirer.prompt(questions);

        // 1. Save Config
        const configPath = path.join(process.cwd(), 'autoflow.config.json');
        fs.writeFileSync(configPath, JSON.stringify(answers, null, 2));
        log.success('Configuration saved to autoflow.config.json');

        // 2. Generate Dockerfile if missing
        const dockerfilePath = path.join(process.cwd(), 'Dockerfile');
        if (!fs.existsSync(dockerfilePath)) {
            const dockerfileContent = `# Generated by AUTOFLOW
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE ${answers.appPort}

CMD ["npm", "start"]
`;
            fs.writeFileSync(dockerfilePath, dockerfileContent);
            log.success('Generated default Dockerfile (Node.js 18)');
        } else {
            log.warning('Dockerfile already exists, skipping generation.');
        }

        // 3. Generate .dockerignore
        const ignorePath = path.join(process.cwd(), '.dockerignore');
        if (!fs.existsSync(ignorePath)) {
            fs.writeFileSync(ignorePath, 'node_modules\n.git\n.env\nautoflow.config.json');
            log.success('Generated .dockerignore');
        }

        log.info('\nInitialization complete!');
        log.info(`You can now run "autoflow deploy" to ship your code!`);

    } catch (err) {
        log.error('Initialization failed: ' + err.message);
    }
}

module.exports = init;
